### ISSUE TITLE
Hi sensei!

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [AswinOP/device_xiaomi_veux#1]
How u made the ROM compilation?
What do I needed?
Can you make some thing like a tutorial?

**Comment by rk134** [comment]
Dude, you need to stop. This isn't how you ask for help, and you especially don't go around making threads on the issue tab.

**Comment by LUISMAGAIVER341** [comment]
Shut up.
Idiots like u think that ask for help is a problem.
I just asked. Nothing more.
So if u can't help, just say : "I Can't"

**Comment by rk134** [comment]
Ahahaha, noobs like you think that asking for help like this isn't a problem.

Address skill issues when?

**Comment by LUISMAGAIVER341** [comment]
Because it isn't!
You don't have humility man.
I know I'm a noob, so I'm asking for help 
And I'm going to fix my lack of skills with people who aren't muggles, idiots like you.

**Comment by LUISMAGAIVER341** [comment]
Because it isn't!
You don't have humility man.
I know I'm a noob, so I'm asking for help 
And I'm going to fix my lack of skills with people who aren't muggles, idiots like you.

**Comment by resist15** [comment]
> Because it isn't! You don't have humility man. I know I'm a noob, so I'm asking for help And I'm going to fix my lack of skills with people who aren't muggles, idiots like you.

there's a time and place for everything and this isn't the place for you asking dumb shit

**Comment by jendermine** [comment]
> Shut up. Idiots like u think that ask for help is a problem. I just asked. Nothing more. So if u can't help, just say : "I Can't"

I'm reporting this to GitHub abuse and support.

**Comment by rk134** [comment]
> Because it isn't! You don't have humility man. I know I'm a noob, so I'm asking for help And I'm going to fix my lack of skills with people who aren't muggles, idiots like you.

1. You don't get help by going around and calling people idiots.
2. It's not because I don't have humility, I'm just pointing out the obvious.
3. Be careful with what you throw at people, you will receive the same abuse back, retard.
